### ISSUE TITLE
project name question

### ISSUE THREAD

**Issue by ped7g** [jimnicholls/zxnftp#1]
Hello, are you aware there already is "zxnftp" project for Next by varmfskii: https://github.com/varmfskii/zxnext_tools/tree/master/zxnftp

ie. my question is, if the project name clash is deliberate (and caused by you if I understand the timeline of both projects), or just accident? If accident, any chance to rename yours, or it is what it is and will stay like this?
(I would prefer to see two different names, but as long as I will put some note on wiki or somewhere, that there are two, I can live with that as well)

Thanks for the info.

**Comment by jimnicholls** [comment]
I wasn't aware of this. I think I had seen zxnext_tools, but had not noticed zxnftp. I guess is it is a obvious name.

I will rename this project. My development hasn't progressed beyond the server parser, and has already stalled.

Interestingly the idea I had through was the opposite. I was going to put the server on the PC and have the client on the Next. I have a need when I'm on the Next to back up files on my SD card to a PC; so it made sense for me that way around.

This was going to be a vehicle to learn asm and .dot dev on the Next. But, yeah, there's intentions and then these actually doing the thing.
